version: '3.8'

services:
  # 1. Baza danych (PostgreSQL)
  postgres:
    image: postgres:15-alpine
    container_name: booking_postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=event_booking_system_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Cache i Locki (Redis)
  redis:
    image: redis:alpine
    container_name: booking_redis
    restart: always
    ports:
      - "6379:6379"

  # 3. Kolejka wiadomości (RabbitMQ)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: booking_rabbitmq
    restart: always
    ports:
      - "5672:5672"   # Port dla aplikacji (Spring)
      - "15672:15672" # Port dla panelu zarządzania (przeglądarka)
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

volumes:
  postgres_data: # Wolumen, aby dane nie znikały po restarcie kontenera