spring:
  application:
    name: High-Traffic-Event-Booking-System

  # Konfiguracja Bazy Danych
  datasource:
    url: jdbc:postgresql://localhost:5432/event_booking_system_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Na start 'update' jest OK, na produkcji używa się 'validate'
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Konfiguracja Redis
  data:
    redis:
      host: localhost
      port: 6379

  # Konfiguracja RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin